import { ExtURL } from "../../../../../components";

import forbes from "./assets/forbes.png";
import mapping from "./assets/mappingProblem.jpg";
import tetris from "./assets/tetrisEffect.jpg";
// https://www.theverge.com/2018/11/18/18099272/tetris-effect-perfect-game-red-dead-redemption-2-modern-games-overwhelming
import superhot from "./assets/superhot.jpg";
// https://uploadvr.com/new-modes-endless-arenas-superhot-vr/
import nier from "./assets/nier.jpg";

export const post = {
	id:4,
	url:'may_3_2021',
	metadata:{
		umbrella:'gamedev',
		post_date:"May 3, 2021",
		description:"Originally from a wordpress website called \"SimpleDevs\", I've migrated it to this personal blogging platform."
	},
	title:"VR-Centric Game Design: The Conundrum of Immersive Experiences",
	content:[
		"Hello everyone, I'm back for a new blog post.",
		"After last week's post discussing different game ideas, I thought it would be a good opportunity to take a breather and mull about some thoughts I was personally having about Virtual Reality in gaming.",
		{
			type:'jsx',
			content:(<i>I'd also like to take a second to emphasize the opinions I will express in this blog post are purely based off of anecdotal evidence and are not meant to be an all-encompassing perspective on the industry as a whole. However, they are informed by observations made by games I've played and general trends seen among these games.</i>)
		},
		{
			type:"header",
			level:'3',
			content:'The state of VR in gaming'
		},
		"It started about a year and a half ago, around the time when I was still in graduate school at Cornell Tech. I was introduced to the wonders of Virtual Reality and the greater sphere of Extended Reality by my professor, Harald Haraldsson. Encouraged by him and my colleagues to invest in VR, I would eventually spend my second semester at school building VR prototypes and projects out of sheer fun. I even performing some research into the user experience of typing mechanisms in VR and attempting to develop my own interface with the help of two colleagues at the time, with interesting results.",
		{
			type:"jsx",
			content: (
				<>
					<span>However, as the months passed, despite the advent of the new Oculus Quest 2 and new VR-centric games, VR has refused to enter the cultural zeitgeist, instead being relegated to the interests of a niche target audience of gamers and enthusiasts. Mainstream media claims that </span>
					<ExtURL href="https://www.forbes.com/sites/barrycollins/2020/05/04/vr-headsets-are-dying-a-lonely-death/">VR has died...</ExtURL>
					<span> and yet, simultaneously, </span>
					<ExtURL href="https://www.techradar.com/news/oculus-quest-2-sales-figures-prove-vr-has-finally-gone-mainstream">VR has gone mainstream</ExtURL>
					<span>.</span>
				</>
			)
		},
		{
			type:'image',
			content:forbes,
			alt:"Google results showing that both VR is dying and simultaneously growing",
			caption:"This will never cease to make me chuckle every time I look at this combination."
		},
		"Which is the truth? In my opinion, neither is the truth - rather, VR is still in its relative infancy as a gaming medium despite it existing for several years. Several factors contribute to this sentiment:",
		{
			type:'jsx',
			content:(
				<ol>
					<li>The risk/reward of investing into VR is still too skewed to the "risk" factor, with too high costs associated with purchasing headsets and relatively too few games (compared to PC and consoles) making the reward only appealing to a select audience of gamers.</li>
					<li>Facebook's dominant presence via the Oculus brand in combination with its data collection practices has deterred some from investing in the Oculus Quest and Quest 2, two of the most successful and appealing headsets in the market otherwise.</li>
					<li>The technology, development pipelines, or VR-centric game design practices simply aren't there yet. Poor implementations of game mechanics lead to problems such as motion sickness due to "vection" (the sensation of movement generated by purely visual stimuli and not by physical movement of the body). and reduced immersion. Companies may not see the investment to create AAA-level games on VR as worthwhile.</li>
					<li>Out of the VR games presently on the market, few VR games actually justify the need to run out and grab a VR headset.</li>
				</ol>
			)
		},
		{
			type:'jsx',
			content: (
				<>
					<span>The first three factors, while incredibly important to consider and are nuanced cases, are worth their own discussions and are not the theme of this blog post. The fourth factor is where my interests primarily lie: </span>
					<strong>"few VR games actually justify the need to run out and grab a VR headset."</strong>
				</>
			)
		},
		{ type:"header", level:'3', content:"The justification for VR" },
		"Whenever I open a VR game, a nagging question begins to eat away at the back of my mind: \"Why is this game in VR?\" Definitely seems insensitive to the developers, VR enthusiasts, and VR gamers, I agree. But this question, in my opinion, needs to be asked about every VR game that is out there. Why does THIS game I'm currently playing need to exist in VR?",
		"I frequently go through a certain pattern whenever I ponder about this question. It goes along like this:",
		{
			type:"jsx",
			content: (
				<ol>
					<li>I initially ask the question: "Why does this game I'm currently playing need to exist in VR?"</li>
					<li>I list out the positive outcomes (ex. emotions, entertainment value) that have come about due to the shift to VR.</li>
					<li>I list out the negative outcomes (ex. motion sickness, complicated control schemes) that have come about due to the shift in VR.</li>
					<li>I think about if this game has a PC equivalent, and if so what are the major differences between the PC version and the VR version.</li>
					<li>I combine my findings into a single evaluation on whether the experience in VR was generally "worth" it in the end.</li>
				</ol>
			)
		},
		{
			type:"jsx",
			content: (
				<>
					<span>This evaluation is surely rife with subjective opinions and is by no means scientific in any way. Perhaps it's just my pessimistic mind hard at work making me doubt everything around me. However, in many cases where I see demo, preview, or gameplay session for a VR game, I sincerely wonder whether if that game I'm looking at is or is not appropriate for a VR experience. Extrapolating from this experience, I am curious whether </span>
					<strong>the justification to purchase and play a game in VR is often missing or lacking for many of these games</strong>
					<span>. This "justification" I speak of ultimately boils down to several key criteria:</span>
				</>
			)
		},
		{
			type:"jsx",
			content: (
				<ul>
					<li>"Does the game's overall gameplay experience take advantage of the affordances offered by VR, going beyond 6-DOF (6 'Degrees of Freedom') motion, grabbing, and hand-tracking?"</li>
					<li>"If a PC port or version exists, how different is the overall gameplay experience between the VR version and the PC version?"</li>
					<li>"On the other hand, if a PC port or version does not exist, would the VR game's gameplay mechanics be translated to a PC version in a way where the overall experience is fundamentally changed?"</li>
				</ul>
			)
		},
		{
			type:"jsx",
			content: (
				<>
					<span>The general vein of thought I'm trying to get at is that the mapping between PC and VR is a key component in the justification argument. I like to ultimately call it the </span>
					<strong>"Mapping Problem"</strong>
					<span>.</span>
				</>
			)
		},
		{ type:"header", level:'3', content:"The \"Mapping Problem\"" },
		"The \"Mapping Problem\" is what I imagine to be every VR game's nightmare, regardless of the genre of the game. The \"Mapping Problem\" is essentially a question of whether the VR experience can be translated into PC without too much change in gameplay mechanics or overall presentation of the game.",
		"The best way I can describe the mapping problem is with this diagram I've drawn up:",
		{
			type:'image',
			content:mapping,
			alt:"The mapping problem in a linear graph"
		},
		"Simply put, whether a game is worth the VR experience is highly dependent on whether that game takes advantage of the affordances offered by VR and whether there is a \"mapping\" between a VR and PC implementation.",
		"A \"mapping\" is an instance where some gameplay mechanic or experience in VR can be replicated on PC and/or console - for example, turning your head is equivalent to rotating the camera via mouse movement. Mappings are not necessarily based solely on gameplay mechanics either; visual and/or emotional experiences can also be mapped as well. For example, the enhanced feeling of fear and claustrophobia in a VR horror game is a weak mapping to the PC game because the player's sense of fear is amplified by the increased sense of spatial awareness offered by VR as opposed to just seeing scary things on a PC monitor.",
		{
			type:"jsx",
			content: (
				<>
					<strong>Games that have a high likelihood of a strong map between these implementations face a weakened justification for being implemented in VR</strong>
					<span>. After all, why would someone play the VR version of a game if they can purchase it for their PC and/or console where it is more accessible and more likely to get the same or similar experience? On the flip side, </span>
					<strong>games that have a weak map between these implementations face a stronger justification for being implemented in VR</strong>
					<span>. If the VR version is different enough, maybe it really is worth at least trying out, right?</span>
				</>
			)
		},
		{ type:"header", level:'3', content:"A \"bad\" port VS. a \"bad\" game" },
		{
			type:"jsx",
			content: (
				<>
					<strong>The Mapping problem is not a valuation of the quality of a game in of itself</strong>
					<span>. A game's quality is defined by its mechanics, gameplay experience and loop, visual/audio quality, etc. for sure, but </span>
					<strong>the Mapping problem is a question of how well that game is fit for a VR experience in particular</strong>
					<span>. Great games that traditionally work well on PC and/or console may not necessarily be the best fit for VR; likewise, games that function very well in VR may not necessarily be the best fit for PC and/or consoles.</span>
				</>
			)
		},
		{
			type:'image',
			content:tetris,
			alt:"Promotional art depicting the gameplay of Tetris Effect",
			caption:(
				<>
					<span>Source: The Verge - (</span>
					<ExtURL href="https://www.theverge.com/2018/11/18/18099272/tetris-effect-perfect-game-red-dead-redemption-2-modern-games-overwhelming">https://www.theverge.com/2018/11/18/18099272/tetris-effect-perfect-game-red-dead-redemption-2-modern-games-overwhelming</ExtURL>
					<span>)</span>
				</>
			)
		},
		{
			type:"jsx",
			content: (
				<>
					<span>Take the game "Tetris Effect" for example. This game is an incredible game, easily a must-own for Tetris fans and VR enthusiasts all around. I could go deeper into the merits of this game, but that's not why I am mentioning it here. The game "Tetris Effect" is a great game, but is its VR counterpart worth playing? If Reddit posts are anything to go by (</span>
					<ExtURL href="https://www.reddit.com/r/TetrisEffect/comments/ayxk3f/is_tetris_effect_still_good_without_the_vr_headset/">here</ExtURL>
					<span>, </span>
					<ExtURL href="https://www.reddit.com/r/Tetris/comments/9w8l37/has_anyone_here_been_playing_tetris_effect/">here</ExtURL>
					<span>, </span>
					<ExtURL href="https://www.reddit.com/r/gaming/comments/a754gq/is_tetris_effect_worth_the_purchase_without_vr/">here</ExtURL>
					<span>, and </span>
					<ExtURL href="https://www.reddit.com/r/PSVR/comments/apdedj/is_tetris_effect_worth_it_just_to_play_it_in_vr/">here</ExtURL>
					<span>), it would seem that the general sentiment is leaning towards VR being either an accessory or enhanced experience. Most comments on these posts of this nature declare that "Tetris Effect" is just as good on the TV as it is in VR" or something similar. If we take these players' words at face value, then I am inclined to believe that </span>
					<strong>the key attractive feature is also strongly mapped to non-VR versions of the game</strong>
					<span>. If both the gameplay and visual-auditory experience of "Tetris Effect" are easily replicated in non-VR versions of the game, then perhaps "Tetris Effect" is not worth the VR experience. </span>
					<strong>That is not to say that the game is bad or that you should not buy the VR version of "Tetris Effect"... but "Tetris Effect" is not a "good" VR game in that it is ineffective in taking advantage of the VR medium.</strong>
				</>
			)
		},
		{ type:"header", level:'3', content:"Isn't the immersion factor enough justification in of itself?" },
		"I frequently see the argument that sometimes games may not take advantage of all the affordances offered by VR but are nonetheless invaluable experiences hard to replicate elsewhere. This is often a result of the increased sense of immersion players get when putting on a head-mounted display (HMD) and seeing/hearing the world directly through vision and hearing. When removed from the constraints of watching the game from a 2D screen and thrusted into a virtual world, the actions a player takes consequently has more weight. For example, the feeling of dodging arrows or bullets by moving one's head or the increasing sense of claustrophobia derived from being in the middle of a haunted house at night - these are experiences that are amplified by VR and only VR. In fact, some might argue that this sense of immersion is the end goal of VR.",
		{
			type:'image',
			content:superhot,
			alt:"Gameplay screenshot of SUPERHOTt",
			caption:(
				<>
					<span>Source: UploadVR (</span>
					<ExtURL href="https://uploadvr.com/superhot-vr-quest-review/">https://uploadvr.com/superhot-vr-quest-review/</ExtURL>
					<span>)</span>
				</>
			)
		},
		"The question of immersion is also tied to the Mapping problem in the sense that we are evaluating if the VR experience can be replicated via traditional 2D screens as opposed to the HMD. If the game is able to induce a sense of immersion that is far different from what any 2D screen can provide, then that increased sense of immersion may be a key defining feature of a game that fully justifies the VR experience. There certainly is a place for this argument and we must judge each game as a case-by-case scenario if we subject ourselves to the immersion argument.",
		{ type:"header", level:'3', content:"The Mapping Problem is only a part of the bigger issue" },
		{
			type:"jsx",
			content: (
				<>
					<span>The Mapping Problem only serves to explain some of the difficulties lying in VR's path to becoming a mainstream video game medium. Like I've mentioned before, there are other problems that span from development costs to the types of agents involved in the industry. The Mapping Problem is, in a sense, a small part of a bigger topic. </span>
					<strong>The effect that the Mapping Problem has on the greater topic of VR's presence in the industry is intrinsically tied to players' perceptions of what VR actually is and can do</strong>
					<span>.</span>
				</>
			)
		},
		{
			type:"jsx",
			content: (
				<>
					<span>The </span>
					<strong>"Trench" </strong>
					<span>as I like to call it is the area in the "Mapping Problem" where most VR games tend to exist. Between the </span>
					<strong>"Nightmare" </strong>
					<span>(where VR games have no justification for existing in VR) and the </span>
					<strong>"Ideal" </strong>
					<span>(where VR games have every justification for existing in VR), a lot of VR games often inspire the general sentiment of being "enhanced" experiences that fail in some areas in regards to its implementation of VR affordances. This is not necessarily bad in of itself - some might argue that it's in fact a good thing that VR in gaming is at least recognized as a viable medium for playing video games.</span>
				</>
			)
		},
		"But I believe that as long as VR games are labeled as such, VR gaming will never take off entirely on its own and will never gain the traction necessary to evolve into a standalone medium on par with console and PC gaming. Instead, it will be only treated as an immersive experience that gives players an \"enhanced\" feeling and nothing more.",
		{ type:"header", level:'3', content:"How can we avoid the Mapping Problem?" },
		{
			type:"jsx",
			content: (
				<>
					<span>It would behoove us to talk about problems in VR without considering some solutions that may help us get out of those very problems. If we are going to discuss the Mapping Problem, let us think about how we can avoid the Mapping Problem (or at least reduce its effect on VR's potential). </span>
					<strong>To reduce the Mapping Problem's effect on our VR games, we must seek to achieve the "Ideal"</strong>
					<span>, where VR games have every justification for existing in VR and cannot be replicated by PC or consoles.</span>
				</>
			)
		},
		{
			type:"jsx",
			content: (
				<>
					<span>What does it mean to only exist in VR? Following the logic of our previous statements, </span>
					<strong>the gaming experience of VR is typically divided into two types: gameplay experience and immersive experience</strong>
					<span>. Gaming experience involves considerations such as control schemes, user interfaces, and anything that is involved with the "how" of playing games. Simultaneously, the immersive experience involves considerations such as the user experience (which is different from user interfaces), story, and audio/visual fidelity of a game. This all seems kind of obvious... but we have to at least establish a common ground to act as the foundation of our thought exercise. Consequently, </span>
					<strong>we must develop games in accordance to exploring all the possible ways can expand, emphasize, and evolve the gameplay and immersive experiences of VR games.</strong>
				</>
			)
		},
		"Let me introduce you to American computer scientist Steven M. LaValle (early founder and head scientist of Oculus VR until its acquisition by Facebook). LaValle has provided us a certain definition of VR that is popular in academic circles and I believe is also sensible to use as a north star of VR-based game design:",
		{
			type:'quote',
			content:'"The definition of VR: Inducing targeted behavior in an organism by using artificial sensory stimulation, while the organism has little or no awareness of the interference." - Steven M. LaValle'
		},
		"This definition has four distinct components:",
		{
			type:"jsx",
			content:(
				<ol>
					<li><i>Targeted behavior:</i> The organism is having an "experience" that was designed by the creator. Examples include flying, walking, exploring, watching a movie, and socializing with other organisms.</li>
					<li><i>Organism:</i> This could be you, someone else, or even another life form such as a fruit fly, cockroach, fish, rodent, or monkey (scientists have used VR technology on all of these!).</li>
					<li><i>Artificial sensory stimulation:</i> Through the power of engineering, one or more senses of the organism become co-opted, at least partly, and their ordinary inputs are replaced or enhanced by artificial stimulation.</li>
					<li><i>Awareness:</i> While having the experience, the organism seems unaware of the interference, thereby being "fooled" into feeling present in a virtual world. This unawareness leads to a sense of presence in an altered or alternative world. It is accepted as being natural.</li>
				</ol>
			)
		},
		{
			type:"jsx",
			content:(
				<>
					<span>You can read more about the nature of VR in this documentation written by LaValle himself: (</span>
					<ExtURL href="http://lavalle.pl/vr/node3.html">http://lavalle.pl/vr/node3.html</ExtURL>
					<span>).</span>
				</>
			)
		},
		{
			type:"jsx",
			content:(
				<>
					<span>LaValle's definition takes emphasizes that VR must induce a feeling of immersion via artificial sensory stimulation </span>
					<strong>without making the user realize they are being interfered with.</strong>
				</>
			)
		},
		"Taking this definition into account, the aforementioned realization of immersion is simply not enough for VR: it is the method by which immersion is executed that is important for the VR experience. If a player feels immersed by the 6-DOF (degrees of freedom) nature of their headset and controllers but is intrinsically aware that they have to press buttons to pick up items or interact with objects, then there is grounds to argue that this game has some problems in its execution as a VR game.",
		{ type:"header", level:'3', content:"To explore all the possible ways..." },
		"A digression, if you would allow me. Perhaps you have heard of a certain game called \"Nier Automata\". Directed by Yoko Taro, developed by Platinum Games, and published by Square Enix, the game has garnered critical acclaim for a whole slew of reasons (some of which I personally do not see, but that's just my perspective). \"Nier Automata\" is also a really good example of properly using components and stretching them to their logical extremes.",
		"I will not go into the game's story - that has already been explored by many that have come before me. Instead, let me use a certain gameplay aspect employed by this game to demonstrate my point.",
		"At a certain part of the game's story, you are required to play the game from the perspective of a main character named \"9S\". In the universe of \"Nier Automata\", 9S is a Scanner model android designed to infiltrate enemy lines and gather intelligence on the android's enemy: robots. Because of this role, 9S has access to a different toolbox of abilities than the other main character, \"2B\". One of those tools in that toolbox allows the player to \"hack\" enemy robots and hurt them by playing a certain minigame. To put it simply, 9S's combat is interwoven with moments of bullet hell minigames.",
		"I've drafted a diagram depicting how the mechanic plays out (though I highly recommend seeing gameplay first to really understand how this game handles bullet hell mechanics).",
		{
			type:"image",
			content:nier,
			alt:"diagram depicting how gameplay in Nier Automata has the same core basis but comes from various forms"
		},
		"Pay attention to how a single concept and mechanic expands into different game modes. The idea of pointing and shooting initially starts with two basic implementations introduced at the beginning of the game: the hacking minigame (with cubes and lights acting as an abstraction of data) and 3D flying sections (constrained with 2D movement but featuring additional abilities). Then, we see that concept extrapolated into different game modes that build upon those initial modes:",
		{ 
			type:"jsx",
			content:(
				<ul>
					<li>sometimes the camera moves behind the player's triangular avatar in the hacking game</li>
					<li>sometimes the mechanics for movement are kept but the perspective morphs into a 3D isometric view with no shooting mechanics</li>
					<li>when the player is outside of the hacking game, combat employs elements of bullet hell shooters with enemies shooting avoidable bullets at you</li>
					<li>at one point we see an amalgamation of the hacking minigame and 3D movement combined, with the player navigating data abstracted as a world of cubes and lights</li>
				</ul>
			)
		},
		{
			type:'jsx',
			content:(
				<>
					<strong>My point is that instead of using multiple complex mechanics to build the combat gameplay, the game decides to explore a select few mechanics - in doing so, the game has the leeway to really expand on those mechanics while being internally consistent in its user experience</strong>
					<span>. In the context of "Nier Automata", combat strays never too far away from the singular idea of avoiding bullets and shooting back at them. By honing in on these select few mechanics, the developers of the game are given the opportunity to be creative with these mechanics while not alienating players too much. Simultaneously, players are conditioned to adapt to these mechanics from the beginning of the game and thus may be excited to see those mechanics transformed and explored to their fullest extent over time.</span>
				</>
			)
		},
		{ type:"header", level:'3', content:"What does this have to do with VR?" },
		{
			type:"jsx",
			content:(
				<>
					<strong>I believe that VR needs to employ a similar mentality of game design in order to really make the VR experience stand out</strong>
					<span>. However, the only caveat is that instead of focusing on button schemes/combinations from the conceptual level, the developer(s) must focus on exploring mechanics that are unique to VR alone. The reason? The Mapping Problem. By focusing on a VR-only mechanic from the get-go, the chances become higher that developers will stumble upon a variation or game mode that truly is focused on VR. This in turn will make the proposition for VR much more appealing.</span>
				</>
			)
		},
		"I've brainstormed a list of VR-only mechanics we can explore:",
		{
			type:"jsx",
			content:(
				<ul>
					<li>Grabbing</li>
					<li>6-DOF tracking (controllers)</li>
					<li>6-DOF tracking (headset)</li>
					<li>Spatial audio (assuming you are using a spacializer in your audio implementation)</li>
					<li>Hand Tracking (for Oculus systems)</li>
					<li>Finger tracking (for SteamVR)</li>
				</ul>
			)
		},
		{
			type:"jsx",
			content:(
				<>
					<span>From that list, </span>
					<strong>we'll need to use one or more of these mechanics, solidify a concept of gameplay, and then ideate extremely hard to discover all the possible ways game modes can come from that concept</strong>
					<span>. Of course, this does not necessarily mean that a game developer has to be minimalistic in their game mechanics. Minimalist or not, what's important is that a proper exploration of different ideas is performed with VR in mind.</span>
				</>
			)
		},
		{ type:'header', level:'3', content:"Obligatory ending summary" },
		{
			type:'jsx',
			content:(
				<ul>
					<li>The Mapping Problem - a possible explanation for why VR has not become as popular as one might expect</li>
					<li>VR is more than just "feeling immersed" - players have to convinced that their senses were not hijacked.</li>
					<li>The Mapping Problem can be avoided one way by using the "Nier Automata" design philosophy on game mechanics.</li>
				</ul>
			)
		},
		"Games like \"Half Life: Alyx\" and \"Beat Saber\" have fortunately managed to garner the attention of popular culture and have introduced many to the world of VR gaming. Maybe we're beginning to see a turnaround where VR is on the cusp of becoming recognized by a greater number of gamers. I don't have the clairvoyance to declare what'll definitely happen in the future, but I do have high hopes. However, if games continue to remain in the \"Trench\" in their execution, then I fear that VR will soon sink back into relative obscurity.",
		{
			type:'line'
		},
		"Thank you for reading my post. This time around I was a little bit pessimistic about VR, but I hope it has at least inspired someone to think about where VR stands as a gaming medium.",
		"I hope you all have a good day and are staying safe during these trying times."
	]
}